const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday'];
const DAY_ALIASES={mon:'Monday',monday:'Monday',tue:'Tuesday',tues:'Tuesday',tuesday:'Tuesday',wed:'Wednesday',weds:'Wednesday',wednesday:'Wednesday',thu:'Thursday',thur:'Thursday',thurs:'Thursday',thursday:'Thursday',fri:'Friday',friday:'Friday'};
const SUBJECTS=['physics','chemistry','biology','science','combined science','maths','mathematics','english','english language','english literature','history','geography','computing','computer science','ict','pe','physical education','art','music','drama','french','spanish','german','religious studies','rs','pshe','design technology','dt','food','business','economics','psychology','sociology','form','tutorial'];
const STORE='teacherTimetableManager_v3';
const DEFAULT_PERIODS=[['08:45','09:45'],['09:45','10:45'],['11:05','12:05'],['12:05','13:05'],['14:00','15:00'],['15:00','16:00']];
let state=loadState();
let candidates=[];
let extractedText='';
let pdfjsLibRef=null;

function loadState(){try{let x=JSON.parse(localStorage.getItem(STORE)||'null');if(x&&Array.isArray(x.lessons))return {...x,periods:Array.isArray(x.periods)&&x.periods.length?x.periods:DEFAULT_PERIODS};}catch(e){}return {lessons:[],periods:DEFAULT_PERIODS.map(x=>[...x])};}
function persist(){localStorage.setItem(STORE,JSON.stringify(state));renderAll();}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function uid(){return 'l_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function mins(t){let m=String(t||'').match(/(\d{1,2}):(\d{2})/);return m?(+m[1]*60+ +m[2]):0}
function fmtDuration(a,b){let d=Math.max(0,mins(b)-mins(a));return d}
function toast(msg){let e=document.getElementById('toast');e.textContent=msg;e.classList.add('show');clearTimeout(window.__ttToast);window.__ttToast=setTimeout(()=>e.classList.remove('show'),2200)}
function showPage(name){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+name));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===name));let map={week:['Your week','A clear view of lessons, rooms and classes.'],import:['Smart Import','Turn timetable images and documents into editable lessons.'],lessons:['All lessons','Find and manage every teaching slot.'],settings:['Settings','Configure periods and manage your data.']};document.getElementById('pageTitle').textContent=map[name][0];document.getElementById('pageSub').textContent=map[name][1];if(name==='settings')renderPeriodEditor();if(name==='lessons')renderLessonList()}
document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));

function renderAll(){renderWeek();renderStats();renderLessonList();}
function renderStats(){let total=state.lessons.length;let m=state.lessons.reduce((a,l)=>a+fmtDuration(l.start,l.end),0);let classes=new Set(state.lessons.map(l=>l.className).filter(Boolean));let jsDay=new Date().getDay(),today=DAYS[jsDay-1];document.getElementById('statLessons').textContent=total;document.getElementById('statHours').textContent=(m/60).toFixed(m%60?1:0)+'h';document.getElementById('statClasses').textContent=classes.size;document.getElementById('statToday').textContent=today?state.lessons.filter(l=>l.day===today).length:0}
function allTimeSlots(){let set=new Set(state.periods.map(p=>p.join('|')));state.lessons.forEach(l=>set.add([l.start,l.end].join('|')));return [...set].map(x=>x.split('|')).filter(x=>x[0]).sort((a,b)=>mins(a[0])-mins(b[0]))}
function renderWeek(){let g=document.getElementById('weekGrid');let today=DAYS[new Date().getDay()-1];let slots=allTimeSlots();let html='<div class="head">Time</div>'+DAYS.map(d=>`<div class="head ${today===d?'today-head':''}">${d}${today===d?' · Today':''}</div>`).join('');for(let slot of slots){html+=`<div class="time">${esc(slot[0])}<br><span>${esc(slot[1])}</span></div>`;for(let day of DAYS){let items=state.lessons.filter(l=>l.day===day&&l.start===slot[0]).sort((a,b)=>String(a.subject).localeCompare(String(b.subject)));html+=`<div>${items.length?items.map(l=>`<div class="lesson" onclick="openLessonModal('${l.id}')"><b>${esc(l.subject||'Lesson')}</b><span>${esc([l.className,l.room].filter(Boolean).join(' · '))}</span></div>`).join(''):'<div class="empty">—</div>'}</div>`}}g.innerHTML=html}
function renderLessonList(){let box=document.getElementById('lessonList');if(!box)return;let q=(document.getElementById('lessonSearch')?.value||'').trim().toLowerCase();let arr=[...state.lessons].sort((a,b)=>DAYS.indexOf(a.day)-DAYS.indexOf(b.day)||mins(a.start)-mins(b.start)).filter(l=>!q||[l.day,l.subject,l.className,l.room].join(' ').toLowerCase().includes(q));box.innerHTML=arr.length?arr.map(l=>`<div class="lesson-row"><div><b>${esc(l.day.slice(0,3))}</b><br><small>${esc(l.start)}–${esc(l.end)}</small></div><div><b>${esc(l.subject||'Lesson')}</b><br><small>${esc([l.className,l.room].filter(Boolean).join(' · ')||'No class/room')}</small></div><button class="btn" onclick="openLessonModal('${l.id}')">Edit</button></div>`).join(''):'<div class="notice info">No lessons match.</div>'}

function initModalDays(){document.getElementById('fDay').innerHTML=DAYS.map(d=>`<option>${d}</option>`).join('')}
function openLessonModal(id=''){let l=state.lessons.find(x=>x.id===id);document.getElementById('modalTitle').textContent=l?'Edit lesson':'Add lesson';document.getElementById('editId').value=l?.id||'';document.getElementById('fDay').value=l?.day||'Monday';document.getElementById('fSubject').value=l?.subject||'';document.getElementById('fStart').value=l?.start||state.periods[0]?.[0]||'09:00';document.getElementById('fEnd').value=l?.end||state.periods[0]?.[1]||'10:00';document.getElementById('fClass').value=l?.className||'';document.getElementById('fRoom').value=l?.room||'';document.getElementById('fNotes').value=l?.notes||'';document.getElementById('deleteLessonBtn').style.display=l?'inline-block':'none';document.getElementById('lessonModal').classList.add('open')}
function closeLessonModal(){document.getElementById('lessonModal').classList.remove('open')}
function saveLessonFromModal(){let id=document.getElementById('editId').value;let l={id:id||uid(),day:document.getElementById('fDay').value,subject:document.getElementById('fSubject').value.trim(),start:document.getElementById('fStart').value,end:document.getElementById('fEnd').value,className:document.getElementById('fClass').value.trim(),room:document.getElementById('fRoom').value.trim(),notes:document.getElementById('fNotes').value.trim()};if(!l.subject||!l.start||!l.end){toast('Add a subject, start and end time.');return}let i=state.lessons.findIndex(x=>x.id===id);if(i>=0)state.lessons[i]=l;else state.lessons.push(l);persist();closeLessonModal();toast(id?'Lesson updated':'Lesson added')}
function deleteCurrentLesson(){let id=document.getElementById('editId').value;if(!id)return;state.lessons=state.lessons.filter(x=>x.id!==id);persist();closeLessonModal();toast('Lesson deleted')}

function renderPeriodEditor(){let box=document.getElementById('periodEditor');box.innerHTML=state.periods.map((p,i)=>`<div style="display:grid;grid-template-columns:55px 1fr 1fr auto;gap:7px;align-items:center;margin-bottom:8px"><small style="color:var(--muted)">P${i+1}</small><input class="period-start" type="time" value="${esc(p[0])}" style="border:1px solid #30425f;background:#0c1627;color:var(--text);padding:8px;border-radius:8px"><input class="period-end" type="time" value="${esc(p[1])}" style="border:1px solid #30425f;background:#0c1627;color:var(--text);padding:8px;border-radius:8px"><button class="btn" onclick="removePeriod(${i})">×</button></div>`).join('')}
function addPeriod(){let last=state.periods[state.periods.length-1]||['09:00','10:00'];let s=mins(last[1]),e=s+60;state.periods.push([`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`,`${String(Math.floor(e/60)).padStart(2,'0')}:${String(e%60).padStart(2,'0')}`]);renderPeriodEditor()}
function removePeriod(i){state.periods.splice(i,1);renderPeriodEditor()}
function savePeriods(){let s=[...document.querySelectorAll('.period-start')],e=[...document.querySelectorAll('.period-end')];state.periods=s.map((x,i)=>[x.value,e[i].value]).filter(x=>x[0]&&x[1]);persist();toast('Periods saved')}
