async function handleFiles(files){for(let file of files){try{setStatus(`Reading ${file.name}…`,5);let ext=file.name.split('.').pop().toLowerCase();let result=[];if(file.type.startsWith('image/'))result=await parseImageFile(file);else if(file.type==='application/pdf'||ext==='pdf')result=await parsePdfFile(file);else if(ext==='docx')result=await parseDocxFile(file);else if(['xlsx','xls','csv'].includes(ext))result=await parseSheetFile(file);else result=parsePlainText(await file.text(),file.name);candidates.push(...result);candidates=dedupeCandidates(candidates);renderCandidates();setStatus(`Finished ${file.name}. ${result.length} lesson${result.length===1?'':'s'} detected.`,100,'good')}catch(e){console.error(e);setStatus(`Could not read ${file.name}: ${e.message||e}`,100,'warn')}}}
async function parseImageFile(file){setStatus(`Improving image for OCR…`,12);let dataUrl=await preprocessImage(file);let res=await Tesseract.recognize(dataUrl,'eng',{logger:m=>{if(m.status==='recognizing text')setStatus(`Reading image text… ${Math.round((m.progress||0)*100)}%`,20+(m.progress||0)*70)}});let tsv=res.data.tsv||'';let words=parseTsv(tsv);extractedText += `\n--- ${file.name} ---\n${res.data.text||''}\n`;return words.length?parseOCRLayout(words,file.name):parsePlainText(res.data.text||'',file.name)}
function parseTsv(tsv){let lines=String(tsv).split('\n'),out=[];for(let i=1;i<lines.length;i++){let c=lines[i].split('\t');if(c.length<12)continue;let level=+c[0],text=c.slice(11).join('\t').trim();if(level===5&&text)out.push({text,conf:+c[10],x0:+c[6],y0:+c[7],x1:+c[6]+ +c[8],y1:+c[7]+ +c[9]})}return out}
async function preprocessImage(file){let url=URL.createObjectURL(file);try{let img=await new Promise((resolve,reject)=>{let i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=url});let scale=Math.min(3,Math.max(1.4,1800/img.width));let c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);let ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,c.width,c.height);let im=ctx.getImageData(0,0,c.width,c.height),d=im.data;let hist=new Array(256).fill(0);for(let i=0;i<d.length;i+=4){let g=Math.round(.299*d[i]+.587*d[i+1]+.114*d[i+2]);hist[g]++}let total=c.width*c.height,lo=0,hi=255,acc=0;while(lo<255&&(acc+=hist[lo])<total*.01)lo++;acc=0;while(hi>0&&(acc+=hist[hi])<total*.01)hi--;let span=Math.max(40,hi-lo);for(let i=0;i<d.length;i+=4){let g=Math.round(.299*d[i]+.587*d[i+1]+.114*d[i+2]);g=Math.max(0,Math.min(255,(g-lo)*255/span));g=Math.round((g-128)*1.18+128);d[i]=d[i+1]=d[i+2]=g}ctx.putImageData(im,0,0);return c.toDataURL('image/png')}finally{URL.revokeObjectURL(url)}}

async function ensurePdfJs(){if(pdfjsLibRef)return pdfjsLibRef;try{pdfjsLibRef=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs');pdfjsLibRef.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';return pdfjsLibRef}catch(e){throw new Error('PDF reader could not load. Check your internet connection and try again.')}}
async function parsePdfFile(file){let pdfjs=await ensurePdfJs();let bytes=new Uint8Array(await file.arrayBuffer());let pdf=await pdfjs.getDocument({data:bytes}).promise;let out=[];for(let p=1;p<=pdf.numPages;p++){setStatus(`Reading PDF page ${p} of ${pdf.numPages}…`,10+80*p/pdf.numPages);let page=await pdf.getPage(p);let tc=await page.getTextContent();let words=tc.items.filter(x=>x.str&&x.str.trim()).map(x=>{let x0=x.transform[4],y=x.transform[5],h=Math.abs(x.height||x.transform[3]||10);return {text:x.str,conf:92,x0,y0:y-h,x1:x0+(x.width||10),y1:y,cx:x0+(x.width||10)/2,cy:y-h/2}});let raw=groupPdfLines(words);extractedText+=`\n--- ${file.name} page ${p} ---\n${raw}\n`;let pageOut=parsePdfLayout(words,file.name+' p'+p);if(!pageOut.length)pageOut=parsePlainText(raw,file.name+' p'+p);out.push(...pageOut)}return dedupeCandidates(out)}
function groupPdfLines(words){let rows=[];for(let w of [...words].sort((a,b)=>b.cy-a.cy||a.x0-b.x0)){let r=rows.find(x=>Math.abs(x.y-w.cy)<Math.max(4,(w.y1-w.y0)*.65));if(!r){r={y:w.cy,words:[]};rows.push(r)}r.words.push(w)}return rows.sort((a,b)=>b.y-a.y).map(r=>r.words.sort((a,b)=>a.x0-b.x0).map(w=>w.text).join(' ')).join('\n')}
function parsePdfLayout(words,source){let inv=words.map(w=>({...w,y0:-w.y1,y1:-w.y0,cy:-w.cy}));return parseOCRLayout(inv,source)}

async function parseDocxFile(file){let buf=await file.arrayBuffer();let r=await mammoth.convertToHtml({arrayBuffer:buf});let doc=new DOMParser().parseFromString(r.value,'text/html');let out=[];doc.querySelectorAll('table').forEach((table,ti)=>{let matrix=[...table.rows].map(row=>[...row.cells].map(c=>c.innerText||c.textContent||''));out.push(...parseGrid(matrix,`${file.name} table ${ti+1}`))});let text=doc.body.innerText||doc.body.textContent||'';extractedText+=`\n--- ${file.name} ---\n${text}\n`;if(!out.length)out=parsePlainText(text,file.name);return dedupeCandidates(out)}
async function parseSheetFile(file){let data=await file.arrayBuffer();let wb=XLSX.read(data,{type:'array'});let out=[];for(let name of wb.SheetNames){let ws=wb.Sheets[name];let matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});let txt=matrix.map(r=>r.join(' | ')).join('\n');extractedText+=`\n--- ${file.name} / ${name} ---\n${txt}\n`;out.push(...parseGrid(matrix,`${file.name} / ${name}`))}return dedupeCandidates(out)}
function parsePastedText(){let t=document.getElementById('pasteText').value;if(!t.trim()){toast('Paste timetable text first.');return}extractedText+=`\n--- Pasted text ---\n${t}\n`;candidates=dedupeCandidates([...candidates,...parsePlainText(t,'pasted text')]);renderCandidates();setStatus(`${candidates.length} possible lesson${candidates.length===1?'':'s'} ready to review.`,100,'good')}

function setStatus(text,pct=0,type='info'){let s=document.getElementById('importStatus'),w=document.getElementById('progressWrap'),b=document.getElementById('progressBar');s.style.display='block';s.className='notice '+type;s.textContent=text;w.style.display=pct>=100?'none':'block';b.style.width=Math.max(0,Math.min(100,pct))+'%'}
function renderCandidates(){let card=document.getElementById('reviewCard');card.style.display='block';let body=document.getElementById('reviewBody');let low=candidates.filter(c=>c.confidence<65).length;document.getElementById('reviewSummary').innerHTML=`<div class="notice ${low?'warn':'good'}">${candidates.length} candidate lesson${candidates.length===1?'':'s'} detected.${low?` ${low} need${low===1?'s':''} a closer check.`:' The detected fields look consistent, but review them before importing.'}</div>`;body.innerHTML=candidates.map((c,i)=>`<tr><td><input type="checkbox" ${c.selected?'checked':''} onchange="candidates[${i}].selected=this.checked"></td><td><select onchange="candidates[${i}].day=this.value">${DAYS.map(d=>`<option ${d===c.day?'selected':''}>${d}</option>`).join('')}</select></td><td><input type="time" value="${esc(c.start)}" onchange="candidates[${i}].start=this.value"></td><td><input type="time" value="${esc(c.end)}" onchange="candidates[${i}].end=this.value"></td><td><input value="${esc(c.subject)}" onchange="candidates[${i}].subject=this.value"></td><td><input value="${esc(c.className)}" onchange="candidates[${i}].className=this.value"></td><td><input value="${esc(c.room)}" onchange="candidates[${i}].room=this.value"></td><td><span class="conf ${c.confidence>=80?'high':c.confidence>=65?'mid':'low'}">${c.confidence}%</span></td></tr>`).join('');document.getElementById('rawExtract').textContent=extractedText.trim()||'No raw extract available.';card.scrollIntoView({behavior:'smooth',block:'start'})}
function selectAllCandidates(v){candidates.forEach(c=>c.selected=v);renderCandidates()}
function applyCandidates(){let chosen=candidates.filter(c=>c.selected&&c.day&&c.start&&c.subject);if(!chosen.length){toast('Select at least one complete lesson.');return}let added=0,skipped=0;for(let c of chosen){let dup=state.lessons.some(l=>l.day===c.day&&l.start===c.start&&normalise(l.subject).toLowerCase()===normalise(c.subject).toLowerCase()&&normalise(l.className).toLowerCase()===normalise(c.className).toLowerCase());if(dup){skipped++;continue}state.lessons.push({id:uid(),day:c.day,start:c.start,end:c.end||addMinutes(c.start,60),subject:c.subject.trim(),className:c.className.trim(),room:c.room.trim(),notes:`Imported from ${c.source||'timetable'}`});added++}persist();candidates=candidates.filter(c=>!c.selected);if(candidates.length)renderCandidates();else document.getElementById('reviewCard').style.display='none';toast(`${added} lesson${added===1?'':'s'} added${skipped?`; ${skipped} duplicate${skipped===1?'s':''} skipped`:''}`);showPage('week')}

function exportData(){let blob=new Blob([JSON.stringify({version:3,exportedAt:new Date().toISOString(),...state},null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='teacher-timetable-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Backup downloaded')}
async function restoreData(file){if(!file)return;try{let x=JSON.parse(await file.text());if(!Array.isArray(x.lessons))throw new Error('No lessons found');state={lessons:x.lessons,periods:Array.isArray(x.periods)&&x.periods.length?x.periods:DEFAULT_PERIODS.map(x=>[...x])};persist();toast('Backup restored')}catch(e){toast('That backup file could not be restored.')};document.getElementById('restoreInput').value=''}
function resetApp(){if(!confirm('Delete all timetable data stored in this browser?'))return;state={lessons:[],periods:DEFAULT_PERIODS.map(x=>[...x])};localStorage.removeItem(STORE);renderAll();renderPeriodEditor();toast('Timetable reset')}

const drop=document.getElementById('dropZone'),fileInput=document.getElementById('fileInput');['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>handleFiles([...e.dataTransfer.files]));fileInput.addEventListener('change',()=>{handleFiles([...fileInput.files]);fileInput.value=''});document.getElementById('lessonModal').addEventListener('click',e=>{if(e.target.id==='lessonModal')closeLessonModal()});
initModalDays();renderAll();
