function normalise(s=''){return String(s).replace(/[\u2013\u2014]/g,'-').replace(/\s+/g,' ').trim()}
function matchDay(s=''){let x=normalise(s).toLowerCase().replace(/[^a-z]/g,'');return DAY_ALIASES[x]||Object.entries(DAY_ALIASES).find(([k])=>x.startsWith(k))?.[1]||null}
function parseTimeText(s=''){let x=String(s).toLowerCase().replace(/\./g,':').replace(/\s/g,'');let m=x.match(/\b([0-2]?\d)[:](\d{2})\b/);if(!m){m=x.match(/\b([0-2]?\d)(\d{2})\b/)}if(!m)return null;let h=+m[1],mm=+m[2];if(h>23||mm>59)return null;return `${String(h).padStart(2,'0')}:${String(mm).padStart(2,'0')}`}
function parseTimeRange(s=''){let times=[...String(s).replace(/\./g,':').matchAll(/\b([0-2]?\d)[:](\d{2})\b/g)].map(m=>`${String(+m[1]).padStart(2,'0')}:${m[2]}`);if(times.length>=2)return [times[0],times[1]];let p=String(s).match(/(?:period|lesson|p)\s*(\d{1,2})/i);if(p){let x=state.periods[+p[1]-1];if(x)return [...x]}if(times.length===1){let x=state.periods.find(p=>p[0]===times[0]);return x?[...x]:[times[0],addMinutes(times[0],60)]}return null}
function addMinutes(t,n){let v=mins(t)+n;return `${String(Math.floor(v/60)%24).padStart(2,'0')}:${String(v%60).padStart(2,'0')}`}
function cleanCell(s=''){return String(s).replace(/\r/g,'').split('\n').map(normalise).filter(Boolean).join('\n')}
function parseLessonCell(cell=''){let raw=cleanCell(cell);let lines=raw.split(/\n|\s{2,}|\s*[|•·]\s*/).map(normalise).filter(Boolean);if(!lines.length)return {subject:'',className:'',room:'',confidence:0};let room='',className='',subject='';for(let line of lines){let rm=line.match(/\b(?:room|rm|lab|gym|hall|studio)\s*[:#-]?\s*([A-Za-z0-9.-]+(?:\s*[A-Za-z0-9.-]+)?)/i);if(rm&&!room)room=normalise(rm[0]);let cm=line.match(/\b(?:year\s*)?(?:[7-9]|1[0-3])\s*[A-Za-z]{0,3}\b|\b(?:L6|U6|KS[345])\b|\b[7-9][A-Z]{1,3}\b|\b1[0-3][A-Z]{1,3}\b/i);if(cm&&!className)className=normalise(cm[0])}
let lower=raw.toLowerCase();let subj=SUBJECTS.sort((a,b)=>b.length-a.length).find(s=>lower.includes(s));if(subj)subject=titleCase(subj);if(!subject){let leftover=lines.find(x=>x!==room&&x!==className&&!parseTimeRange(x)&&!matchDay(x));if(leftover)subject=leftover.replace(/\b(?:room|rm|lab)\b.*$/i,'').replace(/\b(?:year\s*)?(?:[7-9]|1[0-3])\s*[A-Za-z]{0,3}\b.*$/i,'').trim()||leftover}
if(room){room=room.replace(/^rm\b/i,'Room').replace(/^lab\b/i,'Lab')}
let confidence=(subject?45:0)+(className?20:0)+(room?15:0)+Math.min(20,lines.length*5);return {subject:titleCase(subject||''),className,room,confidence:Math.min(96,confidence),raw}}
function titleCase(s=''){return String(s).replace(/\b\w/g,c=>c.toUpperCase()).replace(/\bPe\b/g,'PE').replace(/\bRs\b/g,'RS').replace(/\bIct\b/g,'ICT').replace(/\bDt\b/g,'DT')}
function candidate(day,range,cell,base=50,source=''){let p=parseLessonCell(cell);if(!p.subject||/^(break|lunch|registration|assembly|free|non-contact|planning)$/i.test(p.subject))return null;return {selected:true,day,start:range?.[0]||'',end:range?.[1]||'',subject:p.subject,className:p.className,room:p.room,confidence:Math.round(Math.min(99,(base+p.confidence)/2)),source,raw:p.raw||cell}}
function dedupeCandidates(arr){let out=[],seen=new Set();for(let x of arr.filter(Boolean)){let k=[x.day,x.start,x.subject,x.className].map(v=>String(v||'').toLowerCase()).join('|');if(!seen.has(k)){seen.add(k);out.push(x)}}return out}

function parseGrid(matrix,source='table'){let rows=matrix.map(r=>r.map(cleanCell)).filter(r=>r.some(Boolean));let out=[];if(!rows.length)return out;let headerRow=-1,dayCols={};for(let r=0;r<Math.min(rows.length,8);r++){let map={};rows[r].forEach((c,i)=>{let d=matchDay(c);if(d)map[i]=d});if(Object.keys(map).length>=2){headerRow=r;dayCols=map;break}}
if(headerRow>=0){for(let r=headerRow+1;r<rows.length;r++){let row=rows[r];let range=null;for(let c=0;c<row.length;c++){range=parseTimeRange(row[c]);if(range)break}if(!range){let pIndex=r-headerRow-1;if(state.periods[pIndex])range=[...state.periods[pIndex]]}for(let [ci,day] of Object.entries(dayCols)){let text=row[+ci]||'';if(text&&range){let cand=candidate(day,range,text,85,source);if(cand)out.push(cand)}}}if(out.length)return dedupeCandidates(out)}
let dayRows=[];for(let r=0;r<rows.length;r++){let d=matchDay(rows[r][0]||'');if(d)dayRows.push([r,d])}if(dayRows.length>=2){let header=rows[Math.max(0,dayRows[0][0]-1)]||[];for(let [r,day] of dayRows){for(let c=1;c<rows[r].length;c++){let range=parseTimeRange(header[c]||'')||state.periods[c-1];let text=rows[r][c];if(text&&range){let cand=candidate(day,range,text,82,source);if(cand)out.push(cand)}}}return dedupeCandidates(out)}
return parsePlainText(rows.map(r=>r.join(' | ')).join('\n'),source)}

function parsePlainText(text,source='text'){let lines=String(text).split(/\n+/).map(normalise).filter(Boolean),out=[],day=null,pendingRange=null;for(let i=0;i<lines.length;i++){let line=lines[i];let directDay=matchDay(line);if(directDay&&line.replace(/[^A-Za-z]/g,'').length<14){day=directDay;continue}let foundDay=DAYS.find(d=>line.toLowerCase().includes(d.toLowerCase()));if(foundDay&&line.toLowerCase().trim().startsWith(foundDay.toLowerCase()))day=foundDay;let range=parseTimeRange(line);if(range)pendingRange=range;if(day&&range){let cell=line.replace(/\b(?:mon(?:day)?|tue(?:sday|s)?|wed(?:nesday|s)?|thu(?:rsday|rs|r)?|fri(?:day)?)\b/ig,'').replace(/\b(?:[0-2]?\d[:.]\d{2})(?:\s*[-–—]\s*[0-2]?\d[:.]\d{2})?\b/g,'').replace(/\b(?:period|lesson|p)\s*\d+\b/ig,'').trim();if(cell){let c=candidate(day,range,cell,64,source);if(c)out.push(c)}}else if(day&&pendingRange&&!matchDay(line)&&!parseTimeRange(line)){let c=candidate(day,pendingRange,line,55,source);if(c)out.push(c);pendingRange=null}}
return dedupeCandidates(out)}

function parseOCRLayout(words,source='ocr'){let clean=words.filter(w=>w.text&&w.text.trim()&&(+w.conf||0)>25).map(w=>({...w,text:normalise(w.text),cx:(w.x0+w.x1)/2,cy:(w.y0+w.y1)/2}));let dayWords=[];for(let w of clean){let d=matchDay(w.text);if(d)dayWords.push({...w,day:d})}let unique={};dayWords.forEach(w=>{if(!unique[w.day]||w.conf>unique[w.day].conf)unique[w.day]=w});let headers=Object.values(unique).sort((a,b)=>a.cx-b.cx);if(headers.length<2)return parsePlainText(groupWordsIntoLines(clean),source);
let medianY=headers.map(h=>h.cy).sort((a,b)=>a-b)[Math.floor(headers.length/2)];headers=headers.filter(h=>Math.abs(h.cy-medianY)<Math.max(40,(h.y1-h.y0)*2.4));if(headers.length<2)return parsePlainText(groupWordsIntoLines(clean),source);
let boundaries=[];for(let i=0;i<=headers.length;i++){if(i===0)boundaries.push(-Infinity);else if(i===headers.length)boundaries.push(Infinity);else boundaries.push((headers[i-1].cx+headers[i].cx)/2)}
let timeWords=clean.filter(w=>w.cy>medianY+8&&parseTimeText(w.text));let timeBands=[];for(let w of timeWords.sort((a,b)=>a.cy-b.cy)){let t=parseTimeText(w.text);if(!t)continue;if(!timeBands.some(x=>Math.abs(x.y-w.cy)<14))timeBands.push({y:w.cy,time:t})}if(!timeBands.length){return parsePlainText(groupWordsIntoLines(clean),source)}
let out=[];for(let ti=0;ti<timeBands.length;ti++){let top=ti===0?(medianY+headers[0].y1)/2:(timeBands[ti-1].y+timeBands[ti].y)/2;let bot=ti===timeBands.length-1?Infinity:(timeBands[ti].y+timeBands[ti+1].y)/2;let range=state.periods.find(p=>p[0]===timeBands[ti].time)||[timeBands[ti].time,addMinutes(timeBands[ti].time,60)];for(let di=0;di<headers.length;di++){let ws=clean.filter(w=>w.cy>top&&w.cy<bot&&w.cx>boundaries[di]&&w.cx<boundaries[di+1]&&!parseTimeText(w.text)&&!matchDay(w.text));let cell=groupWordsIntoLines(ws);if(cell.trim()){let avg=ws.reduce((a,w)=>a+(+w.conf||50),0)/Math.max(1,ws.length);let c=candidate(headers[di].day,range,cell,Math.min(88,avg),source);if(c)out.push(c)}}}return dedupeCandidates(out)}
function groupWordsIntoLines(words){let rows=[];for(let w of [...words].sort((a,b)=>a.cy-b.cy||a.x0-b.x0)){let row=rows.find(r=>Math.abs(r.y-w.cy)<Math.max(10,(w.y1-w.y0)*.75));if(!row){row={y:w.cy,words:[]};rows.push(row)}row.words.push(w)}return rows.sort((a,b)=>a.y-b.y).map(r=>r.words.sort((a,b)=>a.x0-b.x0).map(w=>w.text).join(' ')).join('\n')}
